apiVersion: v1
kind: Pod
metadata:
  name: umair-pod
  namespace: umair
  labels:
    app: umair-nginx
spec:
  containers:
  - name: umair-nginx
    image: nginx:latest
    ports:
      - containerPort: 80

